04875 bucket restructure hip
mgoelswirlds/hedera-improvement-proposal pull request #1
Opened 2023-01-17 18:28 UTC by mgoelswirlds

**Description**:
This PR adds the details of a Draft HIP for Bucket restructuring.

**Related issue(s)**:

Fixes #4875

**Notes for reviewer**:
This is my fork and would like a way for the team to add their comments in here.

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2023-01-17 18:37 UTC, mgoelswirlds commented on HIP/hip-641.md
> +hip: 641
I am not sure how the number is picked. But the doc said it is up to the author.

2023-01-19 21:44 UTC, steven-sheehy requested changes

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +We propose changing the current stream data bucket folder structure from node account ID being shard and node ID based in the path.
```suggestion
We propose changing the current stream data bucket folder structure from node account ID based to node ID based. Additionally, we propose incorporating shard into the path to be future compatible with sharding when it's enabled.
```

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +working-group: Richard Bair (@rbair23), Nick Poorman (@nickpoorman), Jasper Potts, Dan aobizyu
Add me too

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +category: Mirror
```suggestion
category: Mirror, Service
```

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +The current folder structure uses an account ID per node. Account IDs are not ideal as a council member will want to change their account ID over time. To future-proof this folder
Somewhere we should define the difference between a node's account ID and the node ID. How are the two assigned and change over their lifetime.

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +By adapting the new node ID based path we provide the council members the flexibility to change their account ids as well as allow only node specific access to the buckets for future community nodes
Doesn't talk about why the need for rollups

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> + - Add a pathType property with values AUTO, ACCOUNT_ID, and NODE_ID with a default of AUTO
Quote the enum values and other properties here and elsewhere.

```suggestion
 - Add a `pathType` property with values `AUTO`, `ACCOUNT_ID`, and `NODE_ID` with a default of AUTO
```

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> + - Add a pathRefreshInterval property with value for eg:1m
```suggestion
 - Add a `pathRefreshInterval` property with a default value of `1m`
```

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +    recordstreams/record0.0.3/
We could also mention how this format is very inconsistent in regards to casing, separators, and duplicating stream name.

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +After a significant amount of time has passed after launching Phase 2, we will remove these properties to default the downloading from the NODE_ID based path.
```suggestion
After a significant amount of time has passed after launching Phase 2, we will remove these properties to default the downloading from the node ID based path.
```

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +    - If successful, update a per node timestamp and boolean to ensure account ID is used until pathRefreshInterval elapses
Why did we reverse the logic from ticket? I think it would be more efficient to query node account IDs first since once it transitions to node ID it can remain that way indefinitely. I've updated the [ticket](https://github.com/hashgraph/hedera-mirror-node/issues/4388) with some fine tuning of the algorithm that can be used here.

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
There's no need to recompress compressed files.
```suggestion
            2023-01-11T23_21.tar
```

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +               - 2023-01-11T23_21_44.001332036Z.rcd.zst
Where are the signatures? Why would the RCD be in a node ID based path in the file?

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
We should talk about why zstd over gzip since that is a change. We should discuss with ops/services if that's something they can change on the consensus node since it's quite inefficient to recompress files in the lambda if we can help it. We'd have to have some good evidence to convince about zstd's benefits.

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +- Read stream files from current location
Read how many stream files? The algorithm doesn't discuss that lambda would have to keep track of where it left off and that later it would delete stream files.

2023-01-19 21:44 UTC, steven-sheehy commented on HIP/hip-641.md
> +- Calculate the node Id based on the current node account id. NodeId = (number portion of) nodeAccountId - 3
Algorithm doesn't discuss that lambda would hash each file so it can discard duplicates.

2023-01-23 16:00 UTC, mgoelswirlds commented on HIP/hip-641.md
> +               - 2023-01-11T23_21_44.001332036Z.rcd.zst
I forgot to add the signature file. Will do that.I misremembered your earlier statement about having signatures in node id based path.Will correct this.

2023-01-23 16:08 UTC, mgoelswirlds commented on HIP/hip-641.md
> +               - 2023-01-11T23_21_44.001332036Z.rcd.zst
I still don't see a problem having the rcd and signature files together in the node based path. Unless there is something I am missing here.

2023-01-23 16:10 UTC, mgoelswirlds commented on HIP/hip-641.md
> +- Read stream files from current location
I still do not know how many stream files, since that will be determined by performance testing. But yes the other parts of that question will need to be addressed.

2023-01-31 14:03 UTC, mgoelswirlds commented on HIP/hip-641.md
> +    - If successful, update a per node timestamp and boolean to ensure account ID is used until pathRefreshInterval elapses
Ok. I reversed it , thinking node account ID path is a backup , so if we didn't find the file at the first location, we would do this. But your reasoning makes sense

2023-01-31 14:12 UTC, mgoelswirlds commented on HIP/hip-641.md
> +      {shard}/event/
This is for the aggregated files.It wouldn't have nodeId right?

2023-01-31 14:41 UTC, mgoelswirlds commented on HIP/hip-641.md
> +    recordstreams/record0.0.3/
I need to understand this better.

2023-01-31 17:28 UTC, mgoelswirlds commented
@steven-sheehy I have addressed all the comments I had answers to.

2023-02-01 20:13 UTC, steven-sheehy commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
I said this previously, but I think your testing actually showed there was improvement with both inner and outer compression, right?

2023-02-02 18:51 UTC, mgoelswirlds commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
That is correct.

2023-02-02 21:12 UTC, steven-sheehy commented on HIP/hip-641.md
> + By adapting the new node ID based path we provide the council members the flexibility to change their account IDs as well as allow only node specific access to the buckets for future community nodes
Formatting here is inconsistent. Should we make this line another list element or remove all list elements?

2023-02-02 21:12 UTC, steven-sheehy commented on HIP/hip-641.md
> +      {shard}/event/
True, missed originally that it was for aggregated.

2023-02-02 21:33 UTC, jnels124 commented on HIP/hip-641.md
> +- Once the limit has reached aggregate the file and write it to the new bucket location.
```suggestion
- Once the limit has been reached, aggregate the file and write it to the new bucket location. 
```

2023-02-02 21:37 UTC, jnels124 commented on HIP/hip-641.md
> +Write access to the new node id based path will be granting access to only specific node path buckets. This would prevent a malicious node to have write access or corrupt other stream files
```suggestion
Write access to the new node id based path will be granting access to only specific node path buckets. This would prevent a malicious node to have write access or corrupt other stream files.
```

2023-02-02 21:45 UTC, steven-sheehy requested changes

2023-02-02 21:45 UTC, steven-sheehy commented on HIP/hip-641.md
> + - Add a `pathType` property with values `AUTO`, `ACCOUNT_ID`, and `NODE_ID` with a default of `AUTO`
Mentions defaulting to AUTO twice. Though we can also just omit the line `Later once consensus nodes get closer to writing to the new path adjust default to AUTO` and always default to AUTO since that's an implementation/cost saving detail.

```suggestion
 - Add a `pathType` property with values `AUTO`, `ACCOUNT_ID`, and `NODE_ID` with a default of `ACCOUNT_ID`
```

2023-02-02 21:45 UTC, steven-sheehy commented on HIP/hip-641.md
> +Create a new lambda function which performs data rollup along with compression.
We should call out that another reason for doing the rollup is to avoid having to rename millions of files. We should also mention this in the rejected ideas. Renaming millions of files has to be done one by one via S3 APIs and would take months. With rollup we can create separate aggregated files while leaving individual files intact for longer period until we've verified authenticity of rollup.

2023-02-02 21:45 UTC, steven-sheehy commented on HIP/hip-641.md
> +All files are cryptographically signed by each node. Same data will be in each file. We would be just downloading data and aggregating it. Record file bytes would be unchanged. Signatures would still
Wondering what sort of ongoing verification we should do before deletion. After we create this large file how do we verify it's not corrupt, has all the files with no break in running hash or missing signatures, etc?

2023-02-02 21:45 UTC, steven-sheehy commented on HIP/hip-641.md
> +- Maintain an in-memory DB which has all the hashes of aggregated files.
DB is probably the wrong terminology. It should probably just be a map. Also, it wouldn't be all the hashes, just the hashes for the current filename being processed.

2023-02-02 21:47 UTC, mgoelswirlds commented on HIP/hip-641.md
> + By adapting the new node ID based path we provide the council members the flexibility to change their account IDs as well as allow only node specific access to the buckets for future community nodes
The reason I did this was the statement not as a list element was relevant to the above two. But will reformat it.

2023-02-02 22:01 UTC, steven-sheehy commented on HIP/hip-641.md
> + - Add a `pathType` property with values `AUTO`, `ACCOUNT_ID`, and `NODE_ID` with a default of `AUTO`
Yes, I wrote the algorithm and agree with it for implementation on the mirror node. I'm saying it's irrelevant to the HIP and just a cost saving mechanism that doesn't need to be called out. For example, if we're saying end of march go live then it wouldn't even make sense to ever have a period that's not AUTO cause it introduces risk of people staying on ACCOUNT_ID.

2023-02-02 22:02 UTC, mgoelswirlds commented on HIP/hip-641.md
> +- Maintain an in-memory DB which has all the hashes of aggregated files.
You mean the current aggregated file correct?

2023-02-02 22:05 UTC, mgoelswirlds commented on HIP/hip-641.md
> +All files are cryptographically signed by each node. Same data will be in each file. We would be just downloading data and aggregating it. Record file bytes would be unchanged. Signatures would still
Need to dig in a little more for this one.

2023-02-02 22:05 UTC, steven-sheehy commented on HIP/hip-641.md
> +- Maintain an in-memory DB which has all the hashes of aggregated files.
Deduplication wouldn't need a map of all files within the rollup file. Just the current RCD filename being processed in lexographical order.

2023-02-02 22:06 UTC, mgoelswirlds commented on HIP/hip-641.md
> +Create a new lambda function which performs data rollup along with compression.
I do not understand why this would be a rejected idea?

2023-02-06 16:22 UTC, xin-hedera commented on HIP/hip-641.md
> +- There have been council members that want to change their account id but haven’t been able to. Aliases can be assigned to accounts only on create. So they might want to create a new account id with
Perhaps just mention council members want to change their account id. alias account is just one specific case falls under the category

2023-02-06 16:43 UTC, mgoelswirlds commented on HIP/hip-641.md
> +
I am not sure what you mean.  Do you mean we should support sharding as part of this HIP?

2023-02-06 16:44 UTC, mgoelswirlds commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
Yes we are compressing individual files and then compress the tarball.

2023-02-06 16:44 UTC, xin-hedera commented on HIP/hip-641.md
> +
user story, the bucket struct needs to support sharding

2023-02-06 16:49 UTC, xin-hedera commented on HIP/hip-641.md
> +- Delete the existing files that have been read from the current bucket location.
there is a large piece missing in the rollup algorithm: how to pick the data file?

The straightforward way without the involvement of address book and file hash and signature verification is for each timestamp group, calculate the hashes of the data file, and pick the one with super majority.

2023-02-06 16:57 UTC, mgoelswirlds commented on HIP/hip-641.md
> +- There have been council members that want to change their account id but haven’t been able to. Aliases can be assigned to accounts only on create. So they might want to create a new account id with
I agree this is an example of a time the council members might want to change the account Id. Don't know all the use cases , so have added an actual case here. I feel this will give a better understanding of the rationale. Maybe I can add `As an example` there

2023-02-06 16:58 UTC, mgoelswirlds commented on HIP/hip-641.md
> +- Maintain an in-memory map which has the hashes for the current file being processed.
This is to check for duplication of files. Making sure we don't have duplicate files from the aggregated files.

2023-02-06 17:04 UTC, xin-hedera commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
why? generally speaking, compressing compressed data won't reduce size much? I assume we think the tarball can be further compressed, any data to support the idea?

2023-02-06 17:06 UTC, steven-sheehy commented on HIP/hip-641.md
> +- Maintain an in-memory map which has the hashes for the current file being processed.
Non signature files

2023-02-06 17:08 UTC, steven-sheehy commented on HIP/hip-641.md
> +               - 2023-01-11T23_21_44.001332036Z.rcd.zst
Need to mention sidecar files

2023-02-06 18:08 UTC, xin-hedera commented on HIP/hip-641.md
> +- Maintain an in-memory map which has the hashes for the current file being processed.
problem is if we just look at the data file hashes and in case a group of, e.g., record files have two set of hashes, we may end up putting the one without super-majority. the uniqueness is already in the filename since it has the timestamp.

2023-02-06 18:12 UTC, steven-sheehy commented on HIP/hip-641.md
> +- Maintain an in-memory map which has the hashes for the current file being processed.
Why is that a problem? That's how the data is now. It's the responsibility of the mirror node to download and verify. We don't want to discard non-majority files as that is a destructive operation where we lose data. We only want to discard duplicates based upon file hash. So if a specific filename resolves one file to hash A and 26 to hash B, we would upload one hash A and one hash B.

2023-02-06 18:27 UTC, xin-hedera commented on HIP/hip-641.md
> +- Maintain an in-memory map which has the hashes for the current file being processed.
not sure if I missed sth from the compressed file structure, what I get is for the same timestamp, there will be only one data file since data files are not put into node id specific path, only signature files are.

2023-02-06 20:05 UTC, xin-hedera commented on HIP/hip-641.md
> +- Delete the existing files that have been read from the current bucket location.
the above comment should no longer apply since we are going to keep all data files

2023-02-06 20:22 UTC, steven-sheehy commented on HIP/hip-641.md
> +- Delete the existing files that have been read from the current bucket location.
Not going to keep all, just all files with distinct contents.

2023-02-06 20:49 UTC, mgoelswirlds commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
Yes. I did actually compress these compressed files and though , the 2nd compression is not significant, there is saving there.
For a 24.5MB folder with several record files etc.
Individual files compressed with zstd and the folder tarred without zstd algorithm - 8.9 MB
Individual files compressed with zstd and the folder tarred with zstd algorithm - 8.2 MB

Like I said it is not a lot of difference , but there is a difference. Hence, I decided to go with this.

2023-02-06 20:52 UTC, mgoelswirlds commented on HIP/hip-641.md
> +
The bucket structure does support sharding out of the box for eg.` {shard}/{nodeID}/balance/YYYY/MM/DD`. Not sure if I am missing something , but what do we need to explicitly do for it? Do you mean handle this in mirror_node, when reading from the node_id based path?

2023-02-06 21:13 UTC, xin-hedera commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
have you considered the extra time needed for the second round compression and decompression? I don't see why it's worth

2023-02-06 21:19 UTC, xin-hedera commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
alternatively, we can choose to leave all the files inside the tar ball decompressed, tar them, and compress the tar file. I do suspect in case we have many data files, the compression ratio will be greater the current design.

2023-02-06 21:21 UTC, mgoelswirlds commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
The time for further compression and decompression wasn't significant either and hence thought it is better to save some storage.But it is an extra step to decompress when we untar. The savings was 2-3%.

2023-02-06 23:01 UTC, xin-hedera commented on HIP/hip-641.md
> +
all i'm saying is support sharding in the bucket structure is one of the user stories and thus we should add it here

2023-02-06 23:12 UTC, mgoelswirlds commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
It will probably be devops who would do it right?

2023-02-07 20:50 UTC, mgoelswirlds commented on HIP/hip-641.md
> +            2023-01-11T23_21.tar.zst
@xin-hedera I have edited the file accordingly to remove outside compression.

2023-02-10 21:35 UTC, mgoelswirlds commented on HIP/hip-641.md
> +- Adding the network name to the path helps:
@steven-sheehy Could you see if this makes sense for network name addition.

2023-02-10 21:35 UTC, mgoelswirlds commented on HIP/hip-641.md
> +Example:
@steven-sheehy Could you see if this makes sense for network name addition.

2023-02-10 21:36 UTC, mgoelswirlds commented on HIP/hip-641.md
> +##### Proposed naming structure:
@steven-sheehy Could you see if this makes sense for network name addition.

2023-02-11 01:16 UTC, steven-sheehy commented
Since I don't have permission to resolve my own comments in this fork, I put a 🚀 at the end of each discussion item that I think can be resolved. That way you can resolve them on your side.

2023-02-11 04:11 UTC, steven-sheehy commented on HIP/hip-641.md
> +- Adding the network name to the path helps:
Looks good.

2023-02-11 04:17 UTC, steven-sheehy commented on HIP/hip-641.md
> +- As a new mirror node operator I'd like to be able to download historical data in the new aggregated format. This will improve the time it takes to startup a new mirror node with all historical data
Could add a use case for network name.

2023-02-11 04:17 UTC, steven-sheehy commented on HIP/hip-641.md
> +The new structure proposes consistent naming.In the future when we start supporting multiple shards, the new bucket structure will automatically work for it without any required changes.
nit
```suggestion
The new structure proposes consistent naming. In the future when we start supporting multiple shards, the new bucket structure will automatically work for it without any required changes.
```

2023-02-11 04:17 UTC, steven-sheehy commented on HIP/hip-641.md
> +    If pathType is `AUTO`:
nit: Formatting error makes lines appear as one.
```suggestion
 - If pathType is `AUTO`:
```

2023-02-11 04:17 UTC, steven-sheehy commented on HIP/hip-641.md
> +Example:
Looks good

2023-02-11 04:26 UTC, steven-sheehy requested changes

2023-02-11 04:26 UTC, steven-sheehy commented on HIP/hip-641.md
> +- For networks that can be reset the network key in the path will start wth the network name prefix followed by a timestamp, as stated in the above testnet example. On a reset, to get the latest netw
```suggestion
- For networks that can be reset the network key in the path will start wth the network name prefix followed by a timestamp, as stated in the above testnet example. On a reset, to get the latest network one would need to filter by the network prefix (e.g. `testnet`) and sort the folders to get the latest network to read from.
```

2023-02-11 04:26 UTC, steven-sheehy commented on HIP/hip-641.md
> +After a significant amount of time has passed after launching Phase two, we will remove these properties to default the downloading from the node ID based path.
We can't remove this logic until phase three completes and all data is either using node ID or been aggregated.

2023-02-11 04:26 UTC, steven-sheehy commented on HIP/hip-641.md
> +        {shard}/event/
Need to update with network

2023-02-11 04:26 UTC, steven-sheehy commented on HIP/hip-641.md
> +     NOTE:File 2022-07-13T08_46_08.041986003Z.rcd.zst appears in 2 separate node folders. These are files with distinct content and when downloaded by the mirror node one of the two file will be sele
```suggestion
     NOTE: File `2022-07-13T08_46_08.041986003Z.rcd.zst` appears in two separate node folders. These are files with distinct content and when downloaded by the mirror node one of the two file will be selected based on the consensus majority.
```

2023-02-11 04:26 UTC, steven-sheehy commented on HIP/hip-641.md
> +##### Proposed naming structure:
Made a suggestion below.

2023-02-11 17:16 UTC, mgoelswirlds commented on HIP/hip-641.md
> +After a significant amount of time has passed after launching Phase two, we will remove these properties to default the downloading from the node ID based path.
Moved it to after phase three

2023-02-13 19:52 UTC, dalvizu commented on HIP/hip-641.md
> +    {network}/{shard}/{nodeID}/balance/
A shortcoming in our existing structure is that by virtue of being very flat, it is not possible to list the contents of these buckets - it would take too long.

Perhaps we should bucket these by year, month and day as well? That would facilitate these being explorable by humans. Today this is accomplished by knowing the format and making queries with wildcards. I think there is room to improve this experience.

2023-02-13 19:59 UTC, dalvizu commented on HIP/hip-641.md
> +The rollup process could be seen as centralized and a single point of failure. Since, the lambda will be deleting files it has already aggregated, this might be pursued as a problem.
Characterizing this as "seen as" implies it is a perception problem. The problem isn't perception though. A single cloud function in a single cloud provider is both centralized and a single point of failure and this is not a perception problem.

Have we discussed or considered how to implement a decentralized solution? Just throwing something out there: We have all of these consensus nodes that can certainly do the roll up and validate a roll up. Perhaps we pick some area where they can all write to, and allow them to delete from their own paths, and then a rollup process would be done on each node: to perform the process and dump results to their own path. Then check to see if everyone else has done this. And if they have and we're the last one, go ahead and write it to this central path and delete your own copy. And periodically check for these rollups if you've already performed your own, and if so validate it. There'd be some concurrency issues to work around, and we'd need to solve for bad actors, but this would mean no central actors and only nodes can delete their own data.

2023-02-13 20:53 UTC, steven-sheehy commented on HIP/hip-641.md
> +    {network}/{shard}/{nodeID}/balance/
We had that and removed it. It's not useful since we'll be rolling these up and deleting them soon after they're created. So there will be a bunch of empty folders.

Besides, it's not true that you can't list the contents of these buckets quickly. In S3 API you specify a marker or prefix to quickly filter out results after. That's how the mirror node efficiently searches for files after a certain date. So you can always list just the files for a certain year, month or day.

2023-02-13 21:17 UTC, steven-sheehy commented on HIP/hip-641.md
> +The rollup process could be seen as centralized and a single point of failure. Since, the lambda will be deleting files it has already aggregated, this might be pursued as a problem.
I might be misunderstanding you, but having each node do the rollup would be incredibly inefficient and negate the advantage of the rollup. The advantage of the rollup is that it dedupes the large stream files across nodes and that it groups the signatures files together. Sounds like you're suggesting only aggregating within a node. Which would be mostly useless for mirror nodes as we'd have to download at least 1/3 of the very large aggregated files for a given period before we could reach consensus on those files.

2023-02-14 22:26 UTC, mgoelswirlds commented on HIP/hip-641.md
> +    {network}/{shard}/{nodeID}/balance/
@dalvizu Does the discussion we had yesterday and above answer your query?

2023-02-14 22:32 UTC, dalvizu commented on HIP/hip-641.md
> +    {network}/{shard}/{nodeID}/balance/
It does, thanks

2023-02-14 22:33 UTC, dalvizu commented on HIP/hip-641.md
> +The rollup process could be seen as centralized and a single point of failure. Since, the lambda will be deleting files it has already aggregated, this might be pursued as a problem.
Based on discussion it sounds like the centralization is acceptable as by using a cloud provider we aren't making things any worse, and that the long term solution is for a council hosted file service

2023-02-14 22:37 UTC, mgoelswirlds commented on HIP/hip-641.md
> +    {network}/{shard}/{nodeID}/balance/
Thanks Dan.

2023-02-15 15:39 UTC, merged